_.num_tombstones  # unused attribute (nasty/_retriever/conversation_retriever.py:36)
_.num_tombstones  # unused attribute (nasty/_retriever/replies_retriever.py:140)
_.num_tombstones  # unused attribute (nasty/_retriever/thread_retriever.py:133)
_format_action_invocation  # unused function (nasty/_util/argparse_.py:24)
_.required  # unused attribute (nasty/cli/main.py:78)
